### ISSUE TITLE
Add support for Android Studio Iguana 2023.2.1 Patch 1

### ISSUE THREAD

**Issue by ryans233** [ChrisCarini/jetbrains-auto-power-saver#312]
Currently Android Studio Iguana 2023.2.1 Patch 1 cannot install this plugin higher than version 3.1.5. And version 3.1.5 does not seem to work with this AS version.

<img width="1294" alt="image" src="https://github.com/ChrisCarini/jetbrains-auto-power-saver/assets/2986572/ad1e8db1-972f-4b4c-96e3-19b64d5b8832">

**Comment by ChrisCarini** [comment]
Hi @ryans233 - thank you for reporting this issue. There was a bug that was fixed in [v3.2.3](https://github.com/ChrisCarini/jetbrains-auto-power-saver/releases/tag/v3.2.3) of this plugin - that version only works with AS `Jellyfish | 2023.3.1 RC 1`, so I would recommend upgrading to that or a newer version, if you are able.

@all-contributors please add @ryans233  for bug
